### ISSUE TITLE
Timezone Issues for DateTime Fields

### ISSUE THREAD

**Issue by JensRavens** [avo-hq/avo#980]
### Steps to Reproduce
1. Make sure your browser's timezone is not UTC (e.g. Europe/Berlin, which is UTC+2 during summer)
2. Go to https://avodemo.herokuapp.com/avo/resources/projects/36/edit (or any other project)
3. Edit the started datetime field to `2021-11-20 08:00:00` via the UI
3. Hit save

### Expected behavior
The show view should display the time, respecting the timezone (displaying 8:00 in the browser)

### Actual behavior
The displayed value is 10:00. Also, every time you go through the edit/save cycle the time increases by 2 hours.

### System configuration
**Avo version**: 2.7

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
Yes, I see the bug.

I'll make sure it's fixed this week.

**Comment by adrianthedev** [comment]
Hey @JensRavens. Apologies for the delay. I got caught up with marketing things. I pushed [pre3](https://rubygems.org/gems/avo/versions/2.9.1.pre3) for you to try out and see if this fixes it.

**There's a tiny breaking change in there**. To be able to cast the time in the browser's time, I did it in the browser (with a JS package). So, if you used `format` (Ruby tokens) on the `date_time` field you'd have to change the tokens to match [luxon tokens](https://moment.github.io/luxon/#/formatting).

Let me know if this fixes it for you.

**Comment by JensRavens** [comment]
I tried that version for a deployed app on heroku. The update worked (at least the tag on the footer seems like that) and somehow it broke the icon 😅
Anyway, it looks like the bug is still here:

https://user-images.githubusercontent.com/928979/176440222-299a3f05-9560-4722-98e4-ca00700e17c8.mov

**Comment by JensRavens** [comment]
- the server is a heroku europe dyno (I think they're running in UTC, but not sure)
- the values in the DB are stored as a normal rails `:datetime`, therefore it's timezoned in memory but stored as UTC in the DB.
- the rails timezone is set to Berlin `config.time_zone = "Berlin"` in `application.rb` (as this is an app exclusively for the german market)
- the browser's timezone is Berlin too
- the avo resource also is as bare-bones as possible: `field :send_at, as: :date_time, default: -> { DateTime.current }`

**Comment by adrianthedev** [comment]
Hey @JensRavens can you give [2.9.2.pre1](https://rubygems.org/gems/avo/versions/2.9.2.pre1) a try? I made some adjustments that should fix it.

**Comment by adrianthedev** [comment]
Hey @JensRavens have you had a chance to test this build?

**Comment by JensRavens** [comment]
@adrianthedev just did a test run and yep - it's fixed :)

**Comment by adrianthedev** [comment]
Phew. That was a nasty one. Thanks!
